# Generated by Django 5.2.8 on 2026-01-06 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CroquisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='croquis_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='croquis_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='croquis.croquissession')),
            ],
        ),
        migrations.CreateModel(
            name='MotifGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motif_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MotifTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='croquis.motifgroup')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motif_tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to='croquis.focus')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_focuses', to='croquis.croquissession')),
            ],
        ),
        migrations.AddField(
            model_name='croquissession',
            name='focuses',
            field=models.ManyToManyField(related_name='sessions', through='croquis.SessionFocus', to='croquis.focus'),
        ),
        migrations.CreateModel(
            name='SessionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tags', to='croquis.croquissession')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_sessions', to='croquis.motiftag')),
            ],
        ),
        migrations.AddField(
            model_name='croquissession',
            name='tags',
            field=models.ManyToManyField(related_name='sessions', through='croquis.SessionTag', to='croquis.motiftag'),
        ),
        migrations.AddConstraint(
            model_name='focus',
            constraint=models.UniqueConstraint(fields=('owner', 'title'), name='unique_focus_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='motifgroup',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_group_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='motiftag',
            constraint=models.UniqueConstraint(fields=('owner', 'group', 'name'), name='unique_tag_in_group_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='sessionfocus',
            constraint=models.UniqueConstraint(fields=('session', 'focus'), name='unique_session_focus'),
        ),
        migrations.AddConstraint(
            model_name='sessiontag',
            constraint=models.UniqueConstraint(fields=('session', 'tag'), name='unique_session_tag'),
        ),
        migrations.AddConstraint(
            model_name='sessiontag',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('session',), name='unique_primary_tag_per_session'),
        ),
    ]
