# Generated by Django 5.2.8 on 2026-01-16 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("croquis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="latest_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="croquis.croquissession",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="total_duration_seconds",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_subject_per_user"
            ),
        ),
    ]
