# Generated by Django 5.2.8 on 2026-01-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("croquis", "0002_subject_latest_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="croquissession",
            name="finalized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
