# Generated by Django 5.2.8 on 2026-01-24 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croquis', '0003_croquissession_finalized_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='croquissession',
            name='next_action',
            field=models.TextField(default='', help_text='次回セッションで意識すること'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='croquissession',
            constraint=models.UniqueConstraint(condition=models.Q(('finalized_at__isnull', True)), fields=('user',), name='unique_user_incomplete_session'),
        ),
    ]
